const pages = [
    {
      title: "Welcome to CNY 2024",
      url: "/",
      previousPage: null,
      nextPage: "/welcome-noble-beings",
      sectionTitle: null,
      sectionIcon: null,
      bgImage: require("../images/background/0-cover.jpg"),
      backgroundAnimation: {
        animationName: 'scaleDownAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "When were you born?",
      url: "/when-were-you-born",
      previousPage: "/welcome-to-cny-2024",
      nextPage: "/welcome-noble-beings",
      sectionTitle: null,
      sectionIcon: null,
      bgImage: require("../images/background/1-introduction.jpg"),
      backgroundAnimation: {
        animationName: 'slideScaleAnimation',
        animationDuration: '30s',
        animationFillMode: 'forwards',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Welcome noble beings",
      url: "/welcome-noble-beings",
      previousPage: "/welcome-to-cny-2024",
      nextPage: "/choose-your-element",
      sectionTitle: "Introduction",
      sectionIcon: require("../images/icons/introduction.svg"),
      bgImage: require("../images/background/1-introduction.jpg"),
      backgroundAnimation: {
        animationName: 'slideScaleAnimation',
        animationDuration: '30s',
        animationFillMode: 'forwards',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Choose your element",
      url: "/choose-your-element",
      previousPage: "/welcome-noble-beings",
      nextPage: "/choose-your-cup",
      sectionTitle: "Element",
      sectionIcon: require("../images/icons/element.svg"),
      bgImage: require("../images/background/2-element.jpg"),
      backgroundAnimation: {
        animationName: 'slideScaleAnimation',
        animationDuration: '30s',
        animationFillMode: 'forwards',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Choose your cup",
      url: "/choose-your-cup",
      previousPage: "/choose-your-element",
      nextPage: "/choose-your-alliance",
      sectionTitle: "Traits",
      sectionIcon: require("../images/icons/traits.svg"),
      bgImage: require("../images/background/2-element.jpg"),
      backgroundAnimation: {
        animationName: 'slideScaleAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Choose your alliance",
      url: "/choose-your-alliance",
      previousPage: "/choose-your-cup",
      nextPage: "/solve-the-riddle",
      sectionTitle: "Alliance",
      sectionIcon: require("../images/icons/alliance.svg"),
      bgImage: require("../images/background/3-trait.jpg"),
      backgroundAnimation: {
        animationName: 'slideScaleAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Solve the riddle",
      url: "/solve-the-riddle",
      previousPage: "/choose-your-alliance",
      nextPage: "/choose-your-path",
      sectionTitle: "Riddle",
      sectionIcon: require("../images/icons/riddle.svg"),
      bgImage: require("../images/background/5-alliance.jpg"),
      backgroundAnimation: {
        animationName: 'slideScaleAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Your crossroads",
      url: "/choose-your-path",
      previousPage: "/solve-the-riddle",
      nextPage: "/solve-the-puzzle",
      sectionTitle: "Path",
      sectionIcon: require("../images/icons/path.svg"),
      bgImage: require("../images/background/4-path.jpg"),
      backgroundAnimation: {
        animationName: 'scaleDownAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Solve the puzzle",
      url: "/solve-the-puzzle",
      previousPage: "/choose-your-path",
      nextPage: "/test-your-calligraphy-skills",
      sectionTitle: "Puzzle",
      sectionIcon: require("../images/icons/puzzle.svg"),
      bgImage: require("../images/background/6-puzzle.jpg"),
      backgroundAnimation: {
        animationName: 'scaleDownAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Test your calligraphy skills",
      url: "/test-your-calligraphy-skills",
      previousPage: "/solve-the-puzzle",
      nextPage: "/what-is-your-wish",
      sectionTitle: "Calligraphy",
      sectionIcon: require("../images/icons/calligraphy.svg"),
      bgImage: require("../images/background/7-calligraphy.jpg"),
      backgroundAnimation: {
        animationName: 'scaleDownAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    // {
    //   title: "Embrace what's in front of you",
    //   url: "/embrace-whats-in-front-of-you",
    //   previousPage: "/test-your-calligraphy-skills",
    //   nextPage: "/pursue-your-dreams",
    //   sectionTitle: "Spot the Difference",
    //   sectionIcon: require("../images/icons/spot-the-difference.svg"),
    //   bgImage: require("../images/background/8-spot-the-difference.jpg"),
    //   backgroundAnimation: {
    //     animationName: 'scaleDownAnimation',
    //     animationDuration: '20s',
    //     animationTimingFunction: 'linear',
    //     animationIterationCount: '1',
    //   },
    // },
    {
      title: "What is your wish?",
      url: "/what-is-your-wish",
      previousPage: "/test-your-calligraphy-skills",
      nextPage: "/pursue-your-dreams",
      sectionTitle: "Wish",
      sectionIcon: require("../images/icons/spot-the-difference.svg"),
      bgImage: require("../images/background/8-spot-the-difference.jpg"),
      backgroundAnimation: {
        animationName: 'scaleDownAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Pursue your dreams",
      url: "/pursue-your-dreams",
      previousPage: "/embrace-whats-in-front-of-you",
      nextPage: "/meet-your-inner-self",
      sectionTitle: null,
      sectionIcon: null,
      bgImage: require("../images/background/9-result.jpg"),
      backgroundAnimation: {
        animationName: 'scaleDownAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
    {
      title: "Meet your inner self",
      url: "/meet-your-inner-self",
      previousPage: "/pursue-your-dreams",
      nextPage: undefined,
      sectionTitle: null,
      sectionIcon: null,
      bgImage: require("../images/background/10-result-animal.jpg"),
      backgroundAnimation: {
        animationName: 'scaleDownAnimation',
        animationDuration: '20s',
        animationTimingFunction: 'linear',
        animationIterationCount: '1',
      },
    },
  ];

export default pages;
